# Generated by Django 4.2.7 on 2023-12-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_client_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='link',
            field=models.URLField(),
        ),
    ]
