# Generated by Django 4.2.7 on 2023-12-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_client_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
