# Generated by Django 4.2.7 on 2023-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role_as_a', models.CharField(max_length=200)),
                ('expertise', models.CharField(max_length=200)),
                ('twitter_link', models.URLField()),
                ('fb_link', models.URLField()),
                ('insta_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('image', models.ImageField(upload_to='ourteam/')),
            ],
        ),
    ]
