# Generated by Django 4.2.7 on 2023-12-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_ourteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('role_as_a', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('description', models.TextField(max_length=700)),
            ],
        ),
    ]
